blank_issues_enabled: true
contact_links:
  - name: GitHub Discussions
    url: https://github.com/actobotics/pyToolkit/discussions
    about: Ask questions and discuss ideas
  - name: Documentation
    url: https://github.com/actobotics/pyToolkit#readme
    about: Read the documentation

